[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gmg"
version = "1.0.0"
authors = [
  { name="Brook Tozer", email="b.tozer@gns.cri.nz" },
]
description = "An open source geophysical forward modelling GUI"
readme = "README.md"
requires-python = ">=3.8.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD 3-Clause License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/btozer/gmg"
"Bug Tracker" = "https://github.com/btozer/gmg/issues"
"Documentation" = "https://btozer.github.io/gmg/html/gmg_documentation.html"

